"""add volunteer application

Revision ID: ae65a68d0fab
Revises: 99e9cc59f9b3
Create Date: 2025-11-02 09:01:46.459813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae65a68d0fab'
down_revision: Union[str, Sequence[str], None] = '99e9cc59f9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_applications_id'), 'volunteer_applications', ['id'], unique=False)
    op.drop_index(op.f('ix_volunteers_id'), table_name='volunteers')
    op.drop_table('volunteers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('languages', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('education_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_student', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('course', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('employer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('employment_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('employer_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notify_employer', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('special_skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('memberships', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preparation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motivation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('emergency_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('availability', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('ref_name_1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ref_relationship_1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ref_length_1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ref_phone_1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ref_name_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ref_relationship_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ref_length_2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ref_phone_2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ref_name_3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ref_relationship_3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ref_length_3', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ref_phone_3', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('agree', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('volunteers_pkey'))
    )
    op.create_index(op.f('ix_volunteers_id'), 'volunteers', ['id'], unique=False)
    op.drop_index(op.f('ix_volunteer_applications_id'), table_name='volunteer_applications')
    op.drop_table('volunteer_applications')
    # ### end Alembic commands ###
