"""add created_at field to Volunteer

Revision ID: b6c709c9101b
Revises: ae65a68d0fab
Create Date: 2025-11-04 04:44:16.471797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c709c9101b'
down_revision: Union[str, Sequence[str], None] = 'ae65a68d0fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_applications', sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_applications', 'created_at')
    # ### end Alembic commands ###
